name: Meta Setup (All-in-One)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  setup-all:
    name: Setup on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Setup Scripts (Linux & macOS)
        run: |
          bash .github/scripts/setup-rust.sh stable
          bash .github/scripts/setup-chain-spec-builder.sh latest
          bash .github/scripts/setup-omni-node.sh latest
          bash .github/scripts/build-parachain.sh stable stable2412
